### ISSUE TITLE
Add example of how to use fourier_encoding

### ISSUE THREAD

**Issue by mirth** [esceptico/perceiver-io#4]
For example for images

**Comment by esceptico** [comment]
Hey!
Already in work. I will add this within the next week.

**Comment by esceptico** [comment]
@mirth 
Sorry for the delay.
Perceiver IO is being implemented in the 🤗 Transformers. I think that soon it will be available to everyone (and there it will be possible to see how the Fourier positional coding is used). Hence, this repository will most likely not be developed further.
