### ISSUE TITLE
Bug in MultiHeadAttention

### ISSUE THREAD

**Issue by nilesh2797** [esceptico/perceiver-io#9]
https://github.com/esceptico/perceiver-io/blob/6b6507334451f61eeb073665b62f00d26f331893/src/perceiver_io/attention.py#L74

in the referenced line `self.scale` should be multiplied instead of the divide, since  it's defined as `self.scale = self.qk_head_dim ** -0.5`. The correct expression should be `attention = (q @ k.transpose(-2, -1) * self.scale)`

-Nilesh

**Comment by esceptico** [comment]
Nice catch!
Sorry for such a dumb mistake. Will fix it today.

**Comment by esceptico** [comment]
Will update package at pypi soon.
